# Generated by Django 4.0.2 on 2022-03-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='photos.category'),
        ),
    ]
